project_id = "lzdhrtcugqnqmyapgmbs"

[functions.asaas-webhook]
verify_jwt = false

[functions.comprador-externo-signup]
[functions.comprador-externo-signup]
verify_jwt = false

[functions.resumo-diario-vendas]
verify_jwt = false


[functions.zapsign-gerar-contrato]
verify_jwt = false

[functions.zapsign-webhook]
verify_jwt = false

[functions.rematricula-2027-checkout]
verify_jwt = false

[functions.rematricula-2027-otp-enviar]
verify_jwt = false

[functions.rematricula-2027-otp-validar]
verify_jwt = false
