project_id = "lzdhrtcugqnqmyapgmbs"

[functions.asaas-webhook]
verify_jwt = false

[functions.comprador-externo-signup]
[functions.comprador-externo-signup]
verify_jwt = false

[functions.resumo-diario-vendas]
verify_jwt = false

